name: RMS
channels:
        - defaults
        - conda-forge
        - menpo
dependencies:
        - python=3.9
        - dlib=19.24
        - pip
        - pip:
                - cmake
                - jupyter
                - matplotlib
                - numpy
                - opencv-contrib-python==4.6.0.66
                - opencv-python==4.6.0.66
                - scikit-learn
                - scipy
